import type { Metadata } from 'next';
import './globals.css';
import Nav from '@/components/navigation/nav';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Next-App',
  description: 'Generated by Rrii_Dev',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('px-6 md:px-12 max-w-7xl mx-auto')}>
        <div>
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
